remote_theme: develinu/just-the-docs

title: Devinu's Blog
description: Devinu's Blog
baseurl: "/"
url: "https://blog.devinu.org"

search_enabled: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/develinu"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# heading_anchors: true

color_scheme: dark

callouts:
  note:
    title: 정보
    color: green
  warning:
    title: 주의
    color: yellow
  error:
    title: 경고
    color: red
